<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>core-modules-jpa</artifactId>
        <groupId>core-framework</groupId>
        <version>${revision}</version>
    </parent>

    <artifactId>core-modules-jpa-hibernate-mysql</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.hibernate.common</groupId>
            <artifactId>hibernate-commons-annotations</artifactId>
            <version>6.0.2.Final</version>
            <exclusions>
                <exclusion>
                    <artifactId>xml-apis</artifactId>
                    <groupId>xml-apis</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.jboss</groupId>
            <artifactId>jandex</artifactId>
            <version>2.4.2.Final</version>
            <exclusions>
                <exclusion>
                    <artifactId>xml-apis</artifactId>
                    <groupId>xml-apis</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>core-framework</groupId>
            <artifactId>core-modules-jpa-common</artifactId>
        </dependency>
        <dependency>
            <groupId>core-framework</groupId>
            <artifactId>core-modules-ddd</artifactId>
        </dependency>
        <dependency>
            <groupId>core-framework</groupId>
            <artifactId>core-modules-mysql</artifactId>
        </dependency>
    </dependencies>

</project>