master:
  push:
    - name: release-build
      docker:
        image: openjdk:21-slim
        volumes:
          - /root/.m2/:/root/.m2/
      stages:
        - name: build-core-dependencies
          script:
            mvn clean deploy -s ./settings.xml
        - name: build-core-parent
          script: 
            mvn clean deploy -s ./settings.xml
        - name: build-core-modules
          script: 
            mvn clean deploy -s ./settings.xml