master:
  push:
    - name: release-build
      docker:
        image: maven:3.9.9-eclipse-temurin-21
        volumes:
          - /root/.m2:copy-on-write
      stages:
        - name: build-core-dependencies
          script:
            mvn clean deploy -s ./settings.xml
        - name: build-core-parent
          script: 
            mvn clean deploy -s ./settings.xml
        - name: build-core-modules
          script: 
            mvn clean deploy -s ./settings.xml