release/*:
  push:
    - name: release-build
      docker:
        image: tencentcom/maven-jdk21
        volumes:
          - /root/.m2:copy-on-write
      stages:
        - name: build-core-dependencies
          script:
            mvn clean deploy -s ./settings.xml
        - name: build-core-parent
          script: 
            mvn clean deploy -s ./settings.xml
        - name: build-core-modules
          script: 
            mvn clean deploy -s ./settings.xml