package core.framework.ddd.mongodb.support;

import com.mongodb.client.result.DeleteResult;
import core.framework.ddd.api.AggregateRoot;
import org.bson.types.ObjectId;
import org.springframework.core.convert.ConversionException;
import org.springframework.core.convert.ConversionService;
import org.springframework.data.mapping.IdentifierAccessor;
import org.springframework.data.mapping.PersistentPropertyAccessor;
import org.springframework.data.mongodb.MongoDatabaseFactory;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.convert.MongoConverter;
import org.springframework.data.mongodb.core.convert.MongoWriter;
import org.springframework.data.mongodb.core.mapping.MongoPersistentEntity;
import org.springframework.data.mongodb.core.mapping.MongoPersistentProperty;
import org.springframework.data.mongodb.core.mapping.MongoSimpleTypes;
import org.springframework.data.util.TypeInformation;
import org.springframework.lang.Nullable;
import org.springframework.util.ClassUtils;

import java.util.Collection;

/**
 * @author ebin
 */
public class ExtendMongoTemplate extends MongoTemplate {

    public ExtendMongoTemplate(MongoDatabaseFactory mongoDbFactory, MongoConverter mongoConverter) {
        super(mongoDbFactory, mongoConverter);
    }

    @Override
    protected <T> T doInsert(String collectionName, T objectToSave, MongoWriter<T> writer) {
        autogeneratedId(objectToSave);
        return super.doInsert(collectionName, objectToSave, writer);
    }

    @Override
    protected <T> Collection<T> doInsertBatch(String collectionName, Collection<? extends T> batchToSave, MongoWriter<T> writer) {
        batchToSave.forEach(this::autogeneratedId);
        return super.doInsertBatch(collectionName, batchToSave, writer);
    }

    @Override
    public DeleteResult remove(Object object) {
        String collectionName = getCollectionName(object.getClass());
        if (object instanceof AggregateRoot agg) {
            maybeEmitEvent(new AggregateRootBeforeDeleteEvent(agg, null, collectionName));
        }
        DeleteResult deleteResult = remove(object, collectionName);

        if (deleteResult.getDeletedCount() > 1 && object instanceof AggregateRoot agg) {
            maybeEmitEvent(new AggregateRootAfterDeleteEvent(agg, null, collectionName));
        }
        return deleteResult;
    }

    private Object convertId(@Nullable Object id, Class<?> targetType) {
        if (id == null || ClassUtils.isAssignableValue(targetType, id)) {
            return id;
        }
        if (ClassUtils.isAssignable(ObjectId.class, targetType)) {

            if (id instanceof String) {

                if (ObjectId.isValid(id.toString())) {
                    return new ObjectId(id.toString());
                }
                return id;
            }
        }
        ConversionService conversionService = getConverter().getConversionService();
        try {
            return conversionService.canConvert(id.getClass(), targetType)
                ? conversionService.convert(id, targetType)
                : getConverter().convertToMongoType(id, (TypeInformation<?>) null);
        } catch (ConversionException conversionException) {
            return getConverter().convertToMongoType(id, (TypeInformation<?>) null);
        }
    }

    private <T> void autogeneratedId(T objectToSave) {
        if (objectToSave == null) {
            return;
        }
        MongoPersistentEntity<?> persistentEntity = getConverter().getMappingContext().getPersistentEntity(objectToSave.getClass());
        if (persistentEntity == null) {
            return;
        }
        MongoPersistentProperty requiredIdProperty = persistentEntity.getRequiredIdProperty();
        IdentifierAccessor identifierAccessor = persistentEntity.getIdentifierAccessor(objectToSave);
        Object identifier = identifierAccessor.getIdentifier();

        if (identifier == null && MongoSimpleTypes.AUTOGENERATED_ID_TYPES.contains(requiredIdProperty.getType())) {
            PersistentPropertyAccessor<T> propertyAccessor = persistentEntity.getPropertyAccessor(objectToSave);
            propertyAccessor.setProperty(requiredIdProperty, convertId(new ObjectId(), requiredIdProperty.getType()));
        }
    }
}
