<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>core.framework</groupId>
        <artifactId>core-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../../core-parent</relativePath>
    </parent>

    <artifactId>core-framework-test-mvc</artifactId>

    <dependencies>
        <dependency>
            <groupId>core.framework</groupId>
            <artifactId>core-modules-kernel</artifactId>
        </dependency>
        <dependency>
            <groupId>core.framework</groupId>
            <artifactId>core-modules-web-undertow</artifactId>
        </dependency>
        <dependency>
            <groupId>core.framework</groupId>
            <artifactId>core-modules-web-security-jwt</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-context</artifactId>
            <version>1.49.0</version> <!-- 与 agent 对应版本，通常与你使用的 agent 的版本一致 -->
        </dependency>
        <dependency>
            <groupId>io.opentelemetry.instrumentation</groupId>
            <artifactId>opentelemetry-instrumentation-annotations</artifactId>
            <version>2.14.0</version>
        </dependency>
    </dependencies>
</project>