<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>core.framework</groupId>
        <artifactId>core-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../../core-parent</relativePath>
    </parent>

    <artifactId>core-framework-test-mvc</artifactId>

    <dependencies>
        <dependency>
            <groupId>core.framework</groupId>
            <artifactId>core-modules-web-undertow</artifactId>
        </dependency>
        <dependency>
            <groupId>core.framework</groupId>
            <artifactId>core-modules-web-security-jwt</artifactId>
        </dependency>

    </dependencies>
</project>