<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>core.framework</groupId>
        <artifactId>core-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../core-parent</relativePath>
    </parent>

    <artifactId>core-modules</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>core-modules-kernel</module>
        <module>core-modules-exception</module>
        <module>core-modules-ddd</module>
        <module>core-modules-json</module>
        <module>core-modules-mysql</module>
        <module>core-modules-shared</module>
        <module>core-modules-cqrs</module>
        <module>core-modules-kafka</module>
        <module>core-modules-web</module>
        <module>core-modules-name-query</module>
        <module>core-modules-starter</module>
    </modules>

    <build>
        <plugins>
<!--            <plugin>-->
<!--                <groupId>com.github.spotbugs</groupId>-->
<!--                <artifactId>spotbugs-maven-plugin</artifactId>-->
<!--                <configuration>-->
<!--                    <includeFilterFile>spotbugs.xml</includeFilterFile>-->
<!--                    <excludeFilterFile>spotbugs-exclude.xml</excludeFilterFile>-->
<!--                </configuration>-->
<!--            </plugin>-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>