<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.2</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>core-framework</groupId>
    <artifactId>core-dependencies</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <distributionManagement>
        <repository>
            <id>ebinsu-ebin-core-core-framework</id>
            <name>core-framework</name>
            <url>https://ebinsu-maven.pkg.coding.net/repository/ebin-core/core-framework/</url>
        </repository>
    </distributionManagement>

    <properties>
        <revision>1.1.3${changelist}</revision>
        <changelist>-SNAPSHOT</changelist>

        <version.jandex>2.4.2.Final</version.jandex>
        <version.mysql-connector-j>9.0.0</version.mysql-connector-j>
        <version.commons-validator>1.9.0</version.commons-validator>
        <version.commons-io>2.16.1</version.commons-io>
        <version.commons-lang3>3.16.0</version.commons-lang3>
        <version.commons-beanutils>1.9.4</version.commons-beanutils>
        <version.mybatis>3.5.13</version.mybatis>
        <version.bson>4.10.2</version.bson>
        <version.logstash-logback-encoder>7.0.1</version.logstash-logback-encoder>
        <version.hibernate-commons>7.0.1.Final</version.hibernate-commons>
        <version.jandex>2.4.2.Final</version.jandex>
        <version.ognl>3.4.2</version.ognl>
        <version.flapdoodle-embed-mongo>4.9.3</version.flapdoodle-embed-mongo>
        <version.mongodb-driver-legacy>4.11.0</version.mongodb-driver-legacy>
        <version.mongodb-driver-sync>5.1.3</version.mongodb-driver-sync>

        <version.flatten-maven-plugin>1.2.2</version.flatten-maven-plugin>
        <version.maven-source-plugin>3.2.1</version.maven-source-plugin>
        <version.maven-checkstyle-plugin>3.1.2</version.maven-checkstyle-plugin>
        <version.checkstyle>9.3</version.checkstyle>
        <version.spotbugs-maven-plugin>4.7.2.1</version.spotbugs-maven-plugin>
        <version.spotbugs>4.7.3</version.spotbugs>
        <version.maven-pmd-plugin>3.20.0</version.maven-pmd-plugin>
        <version.maven-build-cache-extension>1.0.1</version.maven-build-cache-extension>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-name-query</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-name-query-common</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-name-query-jpa</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-name-query-jdbc</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-name-query-mongo</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-web</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-web-common</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-web-undertow</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-exception</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-ddd</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-json</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-mysql</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-jpa-hibernate</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-jpa-common</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-shared</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-cqrs</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-cqrs-query</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-cqrs-command</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-kafka</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-mongodb</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.jboss</groupId>
                <artifactId>jandex</artifactId>
                <version>${version.jandex}</version>
            </dependency>
            <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <version>${version.mysql-connector-j}</version>
            </dependency>
            <dependency>
                <groupId>commons-validator</groupId>
                <artifactId>commons-validator</artifactId>
                <version>${version.commons-validator}</version>
            </dependency>
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>${version.commons-io}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${version.commons-lang3}</version>
            </dependency>
            <dependency>
                <groupId>org.mybatis</groupId>
                <artifactId>mybatis</artifactId>
                <version>${version.mybatis}</version>
            </dependency>
            <dependency>
                <groupId>org.mongodb</groupId>
                <artifactId>bson</artifactId>
                <version>${version.bson}</version>
            </dependency>
            <dependency>
                <groupId>net.logstash.logback</groupId>
                <artifactId>logstash-logback-encoder</artifactId>
                <version>${version.logstash-logback-encoder}</version>
            </dependency>
            <dependency>
                <groupId>org.hibernate.common</groupId>
                <artifactId>hibernate-commons-annotations</artifactId>
                <version>${version.hibernate-commons}</version>
                <exclusions>
                    <exclusion>
                        <artifactId>xml-apis</artifactId>
                        <groupId>xml-apis</groupId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.jboss</groupId>
                <artifactId>jandex</artifactId>
                <version>${version.jandex}</version>
                <exclusions>
                    <exclusion>
                        <artifactId>xml-apis</artifactId>
                        <groupId>xml-apis</groupId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>ognl</groupId>
                <artifactId>ognl</artifactId>
                <version>${version.ognl}</version>
            </dependency>
            <dependency>
                <groupId>commons-beanutils</groupId>
                <artifactId>commons-beanutils</artifactId>
                <version>${version.commons-beanutils}</version>
            </dependency>
            <dependency>
                <groupId>org.mongodb</groupId>
                <artifactId>mongodb-driver-legacy</artifactId>
                <version>${version.mongodb-driver-legacy}</version>
            </dependency>
            <dependency>
                <groupId>de.flapdoodle.embed</groupId>
                <artifactId>de.flapdoodle.embed.mongo.spring30x</artifactId>
                <version>${version.flapdoodle-embed-mongo}</version>
            </dependency>
            <dependency>
                <groupId>org.mongodb</groupId>
                <artifactId>mongodb-driver-sync</artifactId>
                <version>${version.mongodb-driver-sync}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>flatten-maven-plugin</artifactId>
                    <version>${version.flatten-maven-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>${version.maven-source-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-checkstyle-plugin</artifactId>
                    <version>${version.maven-checkstyle-plugin}</version>
                    <dependencies>
                        <dependency>
                            <groupId>com.puppycrawl.tools</groupId>
                            <artifactId>checkstyle</artifactId>
                            <version>${version.checkstyle}</version>
                        </dependency>
                    </dependencies>
                    <configuration>
                        <configLocation>checkstyle.xml</configLocation>
                        <encoding>UTF-8</encoding>
                        <consoleOutput>true</consoleOutput>
                        <failsOnError>true</failsOnError>
                        <linkXRef>false</linkXRef>
                    </configuration>
                    <executions>
                        <execution>
                            <id>validate</id>
                            <phase>validate</phase>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>com.github.spotbugs</groupId>
                    <artifactId>spotbugs-maven-plugin</artifactId>
                    <version>${version.spotbugs-maven-plugin}</version>
                    <dependencies>
                        <dependency>
                            <groupId>com.github.spotbugs</groupId>
                            <artifactId>spotbugs</artifactId>
                            <version>${version.spotbugs}</version>
                        </dependency>
                    </dependencies>
                    <configuration>
                        <includeFilterFile>spotbugs.xml</includeFilterFile>
                    </configuration>
                    <executions>
                        <execution>
                            <id>validate</id>
                            <phase>validate</phase>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-pmd-plugin</artifactId>
                    <version>${version.maven-pmd-plugin}</version>
                    <configuration>
                        <printFailingErrors>true</printFailingErrors>
                        <rulesets>
                            <ruleset>pmd.xml</ruleset>
                        </rulesets>
                    </configuration>
                    <executions>
                        <execution>
                            <id>validate</id>
                            <phase>validate</phase>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>