<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.0</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>core-framework</groupId>
    <artifactId>core-dependencies</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <properties>
        <revision>1.0.0${changelist}</revision>
        <changelist>-SNAPSHOT</changelist>

        <version.mybatis>3.5.11</version.mybatis>

        <version.flatten-maven-plugin>1.2.2</version.flatten-maven-plugin>
        <version.maven-source-plugin>3.2.1</version.maven-source-plugin>
        <version.maven-checkstyle-plugin>3.1.2</version.maven-checkstyle-plugin>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-ddd</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-json</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-mysql</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-jpa-hibernate</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-shared</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>core-framework</groupId>
                <artifactId>core-modules-query-common</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.mybatis</groupId>
                <artifactId>mybatis</artifactId>
                <version>${version.mybatis}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>flatten-maven-plugin</artifactId>
                    <version>${version.flatten-maven-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>${version.maven-source-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-checkstyle-plugin</artifactId>
                    <version>${version.maven-checkstyle-plugin}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>