package core.framework.namedquery.jdbc;

import core.framework.namedquery.NamedQueryService;
import core.framework.namedquery.configuration.NamedQueryConfiguration;
import core.framework.namedquery.jdbc.configuration.JdbcTemplateNamedQueryServiceConfiguration;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;
import org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration;
import org.springframework.boot.jdbc.EmbeddedDatabaseConnection;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * @author ebin
 */
@SpringBootTest(classes = {
    NamedQueryConfiguration.class,
    DataSourceAutoConfiguration.class,
    JdbcTemplateAutoConfiguration.class,
    JdbcTemplateNamedQueryServiceConfiguration.class
})
@AutoConfigureTestDatabase(connection = EmbeddedDatabaseConnection.H2)
public class JdbcTemplateQueryServiceTest {

    @Autowired
    NamedQueryService namedQueryService;
    @Autowired
    JdbcTemplate jdbcTemplate;

    @AfterEach
    public void dropTable() {
        jdbcTemplate.update("""
            drop table test
            """);
    }

    @BeforeEach
    public void createTable() {
        jdbcTemplate.update("""
                create table test (id bigint generated by default as identity,  name varchar(255), primary key (id))
            """);
        jdbcTemplate.update("""
            insert into test (id, name) values (default, 'test')
            """);
    }

    @Test
    public void test() {
        Optional<Map<String, Object>> o = namedQueryService.get("test.1", Map.of("name", "test"));
        Assertions.assertTrue(o.isPresent());
        Map<String, Object> map = o.get();
        Assertions.assertNotNull(map.get("id"));
        Assertions.assertNotNull(map.get("name"));
    }

    @Test
    public void test_select() {
        List<Object> select = namedQueryService.select("test.1", Map.of("name", "test"));
        System.out.println(select);
    }


    @Test
    public void test1() {
        Optional<TestRecordDTO> o = namedQueryService.get("test.2", Map.of("name", "test"));
        Assertions.assertTrue(o.isPresent());
        TestRecordDTO testDTO = o.get();
        Assertions.assertNotNull(testDTO.id());
        Assertions.assertNotNull(testDTO.name());
    }

    @Test
    public void test2() {
        Optional<TestDTO> o = namedQueryService.get("test.3", Map.of("name", "test"));
        Assertions.assertTrue(o.isPresent());
        TestDTO testDTO = o.get();
        Assertions.assertNotNull(testDTO.id);
        Assertions.assertNotNull(testDTO.name);
    }
}
