<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT named-queries (sql* | mongo*)+>
<!ATTLIST named-queries
        namespace CDATA #REQUIRED
        >

<!ELEMENT fragment (#PCDATA | include | trim | where | foreach | choose | if | bind)*>
<!ATTLIST fragment
        id CDATA #REQUIRED
        >

<!ELEMENT sql (#PCDATA | include | trim | foreach | choose | if | bind | where)*>
<!ATTLIST sql
        id CDATA #REQUIRED
        result-class CDATA #REQUIRED>

<!ELEMENT mongo (#PCDATA | include | trim | foreach | choose | if | bind | filter)*>
<!ATTLIST mongo
        id CDATA #REQUIRED
        result-class CDATA #REQUIRED>

<!ELEMENT where (#PCDATA | include | trim | where | foreach | choose | if | bind)*>
<!ELEMENT filter (#PCDATA | include | trim | foreach | choose | if | bind)*>

<!ELEMENT bind EMPTY>
<!ATTLIST bind
        name CDATA #REQUIRED
        value CDATA #REQUIRED
        >

<!ELEMENT include (property+)?>
<!ATTLIST include segmentid CDATA #REQUIRED>

<!ELEMENT property EMPTY>
<!ATTLIST property
        name CDATA #REQUIRED
        value CDATA #REQUIRED
        >

<!ELEMENT trim (#PCDATA | include | trim | where | foreach | choose | if | bind)*>
<!ATTLIST trim
        prefix CDATA #IMPLIED
        prefixOverrides CDATA #IMPLIED
        suffix CDATA #IMPLIED
        suffixOverrides CDATA #IMPLIED
        >

<!ELEMENT foreach (#PCDATA)*>
<!ATTLIST foreach
        collection CDATA #REQUIRED
        open CDATA #IMPLIED
        close CDATA #IMPLIED
        separator CDATA #IMPLIED
        >

<!ELEMENT choose (when* , otherwise?)>
<!ELEMENT when (#PCDATA | include | trim | where | foreach | choose | if | bind)*>
<!ATTLIST when test CDATA #REQUIRED>
<!ELEMENT otherwise (#PCDATA | include | trim | where | foreach | choose | if | bind)*>

<!ELEMENT if (#PCDATA | include | trim | where | foreach | choose | if | bind)*>
<!ATTLIST if test CDATA #REQUIRED>