spring:
  jpa:
    show-sql: true
  security:
    authentication-type: "EMAIL_CODE"
    authorization-patterns:
      - /test
    session:
      domain: "test"
  mail:
    username: 601054510@qq.com
    password: 123
    host: smtp.qq.com
    port: 465
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          port: ${spring.mail.port}
          auth: true
          starttls:
            enable: true
            required: true
  data:
    redis:
      host: 192.168.136.128
      port: 30006
  main:
    banner-mode: "off"
  application:
    name: test
  kafka:
    dispatcher:
      enable: true
      topics: # Topic to subscribe to
        - tp1
      concurrency: 1  # How many consumers to enable
