spring:
  data:
    redis:
      host: 192.168.136.128
      port: 30006
  main:
    banner-mode: "off"
  application:
    name: test
  kafka:
    dispatcher:
      enable: true
      topics: # Topic to subscribe to
        - tp1
      concurrency: 1  # How many consumers to enable
