spring:
  web:
    cors:
      mappings:
        - mapping: /**
          allowed-origins:
            - http://dev.app.com
          allowed-methods:
            - "*"
          allow-credentials: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.136.128:30001/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ebinsu12345!
    name: test
  jpa:
    hibernate:
      show-sql: true
      hbm2ddl: create
      packages-to-scan:
        - core.framework.test.hibernate
        - core.framework.test.demo
  #    mysql:
  #      jdbc-url: jdbc:mysql://192.168.136.128:30001/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
  #      username: root
  #      password: ebinsu12345!
  security:
    login-request:
      authentication-type: "USERNAME_PASSWORD"
      url: "/security/login"
    logout-request:
      url: "/security/logout"
    patterns:
      - /**
    excludePatterns:
      - /test
    security-type: INTERCEPTOR
  #  mail:
  #    username: 601054510@qq.com
  #    password: 123
  #    host: smtp.qq.com
  #    port: 465
  #    properties:
  #      mail:
  #        transport:
  #          protocol: smtp
  #        smtp:
  #          socketFactory:
  #            class: javax.net.ssl.SSLSocketFactory
  #          port: ${spring.mail.port}
  #          auth: true
  #          starttls:
  #            enable: true
  #            required: true
  data:
    redis:
      host: 192.168.136.128
      port: 30006
    mongodb:
      host: 192.168.136.128
      port: 30015
  main:
    banner-mode: "off"
  application:
    name: test
  kafka:
    dispatcher:
      enable: true
      topics: # Topic to subscribe to
        - tp1
      concurrency: 1  # How many consumers to enable